### ISSUE TITLE
Testing/Training on new dataset

### ISSUE THREAD

**Issue by amineboujnah-dev** [Eaphan/BiProDet#13]
I am trying to test the model on my custom dataset (images and their corresponding vlp-16 point cloud), after that I need to train the annotate the dataset in order to train the model but i think the problem is with the .pkl files i need to find a solution. Please help me with the steps if you can and thanks.

**Comment by Eaphan** [comment]
My suggestion is that you first convert it to kitti or waymo dataset format as much as possible. Or you can try to implement the Dataset class yourself.
