### ISSUE TITLE
Can't reduce the number of samples

### ISSUE THREAD

**Issue by amineboujnah-dev** [Eaphan/BiProDet#5]
I am trying to reduce the number of samples for training/testing purpose but I wasn't able to dot that since I have to use the provided pickle info files for segmentation.

**Comment by Eaphan** [comment]
There are 3712 samples for training and the rest 3769 samples for validation. You can reduce the number of samples for training/validation by reading the pickle files and subsampling from the origin list.

**Comment by Eaphan** [comment]
Sorry, can you describe your purpose and script in detail?
