### ISSUE TITLE
about segmentation labels

### ISSUE THREAD

**Issue by ksh11023** [Eaphan/BiProDet#6]
Hi, Thank you for sharing your work!

When generating *train.pkl using kitti_dataste.py, I don't think  'segmenation label' is included.

Can you give me some advise for fixing this issue? 

Thank you.

**Comment by Eaphan** [comment]
You need to replace the *train.pkl files with those I provided. Please refer to readme.md for details.

"Especially, for the 2D auxiliary task of semantic segmentation, we used the instance segmentation annotations as provided in [KINS dataset](https://github.com/qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset). We incorporate mask of instance segmentation in kitti_infos_train/val.pkl and kitti_dbinfos_train.pkl. Please download them in this [link](https://drive.google.com/drive/folders/1cyFt9MqHnKK620IKbRuTN6SiEvJP6r8d?usp=sharing) and replace the original files."
