### ISSUE TITLE
If I don't want to perform a two-dimensional segmentation task, how should I adjust the code?

### ISSUE THREAD

**Issue by 0neDawn** [Eaphan/BiProDet#7]
Dear author! Thank you very much for the code you provided.  I would like to ask, I do not want to perform two-dimensional segmentation tasks (segmentation tasks are temporarily useless to me and will increase training time). How should I adjust in the code?

**Comment by Eaphan** [comment]
Hi. During the training, it's not necessary to compute the get_segmentation_loss int point_head_vote.py. You can also forbid the image_final_head in _3DSSD_Backbone.

**Comment by 0neDawn** [comment]
> Hi. During the training, it's not necessary to compute the get_segmentation_loss int point_head_vote.py. You can also forbid the image_final_head in _3DSSD_Backbone.

Thank you for your reply. now, I know what to do.
