### ISSUE TITLE
Different calibration files

### ISSUE THREAD

**Issue by amineboujnah-dev** [Eaphan/BiProDet#8]
Hello, can someone explain why the kitti dataset contains different calibration files with different values ?
As far as i know the calibration is made once since the position of sensors is known.

**Comment by Eaphan** [comment]
1. There are different scenes in the KITTI dataset.
2. The pose of the camera is also called the extrinsics of the camera (Camera Extrinsics). Compared with the constant internal parameters, the external parameters will change with the camera movement
